ko-nlp/Korpora

Korpora/korpora.py
Korpora/korpora_nsmc.py

usage 입니다.
```python
from Korpora import NSMC
nsmc = NSMC(root_dir='./Korpora/')
print(str(nsmc))
```
```
NSMC
Reference: https://github.com/e9t/nsmc
Naver sentiment movie corpus v1.0
This is a movie review dataset in the Korean language.
Reviews were scraped from Naver Movies.
The dataset construction is based on the method noted in
[Large movie review dataset][^1] from Maas et al., 2011.
[^1]: http://ai.stanford.edu/~amaas/data/sentiment/
Attributes
NSMC.train : size=150000
NSMC.test : size=50000
```
```python
print(str(nsmc.train))
```
```
NSMCData
Naver sentiment movie corpus v1.0. size of data=150000
Attributes:
NSMCData.texts (list[str]) : size=150000
NSMCData.labels (list[int]) : size=150000
```

Show description and attributes Korpus, KorpusData, NSMC, NSMCData (fix #14)

---

Korpora/korpora.py
Korpora/korpora_nsmc.py

Usage example
```python
from Korpora import NSMC
nsmc = NSMC(root_dir='./Korpora/')
for i, row in enumerate(nsmc.train):
if i > 10:
break
print(row)
```
```
('아 더빙.. 진짜 짜증나네요 목소리', 0)
('흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나', 1)
('너무재밓었다그래서보는것을추천한다', 0)
('교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정', 0)
('사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 던스트가 너무나도 이뻐보였다', 1)
('막 걸음마 뗀 3세부터 초등학교 1학년생인 8살용영화.ㅋㅋㅋ...별반개도 아까움.', 0)
('원작의 긴장감을 제대로 살려내지못했다.', 0)
('별 반개도 아깝다 욕나온다 이응경 길용우 연기생활이몇년인지..정말 발로해도 그것보단 낫겟다 납치.감금만반복반복..이드라마는 가족도없다 연기못하는사람만모엿네', 0)
('액션이 없는데도 재미 있는 몇안되는 영화', 1)
('왜케 평점이 낮은건데? 꽤 볼만한데.. 헐리우드식 화려함에만 너무 길들여져 있나?', 1)
('걍인피니트가짱이다.진짜짱이다♥', 1)
```

KorpusData yiels their attributes (fix#19)

---

.github/workflows/lint.yaml
requirements.txt
tests/test_nsmc.py

**개요**
CI 프로세스가 제대로 작동하는지 확인하기 위한 Pull Request Test

PR Test #16

---

Korpora/korpora_korean_petitions.py
tests/test_korean_petitions.py
tests/test_nsmc.py

- master에 있는 모든 테스트 코드가 정상 작동하도록 만들기 위한 PR입니다
- `KoreanPetitionsData`를 초기화할 때 argument 에러가 나서 해당 클래스를 수정하였습니다
- liscense와 description을 추가하였습니다, 제가 임의로 추가한 것이니 수정 가능합니다
- https://github.com/ko-nlp/Korpora/issues/28

Valid test code #28

---

Korpora/korpora.py

- [v] 작성한 코드가 어떤 에러나 경고 없이 실행이 되나요?
- 테스트 코드가 필요하지 않은 수정입니다
- [v] 기존 코드 역시 에러 없이 수행이 되겠죠?
#35 참고
#35 참고

Implement SentencePair & LabeledSentencePair (fix #35)

---

Korpora/__init__.py
Korpora/fetch.py
Korpora/korpora_chatbot_data.py
Korpora/loader.py
tests/test_korean_chatbot_data.py

송영숙 님이 공개해주신 [Korean Chat Data](https://github.com/songys/Chatbot_data)를 개발
[송영숙님 awesome korean data](https://github.com/ko-nlp/Korpora/issues/6)에도 포함되어 있는 데이터
https://github.com/ko-nlp/Korpora/issues/30

Korean Chatbot Data #30

---

Korpora/korpora_nsmc.py

Use default root when NSMC.root_dir is None (fix #37)

---

Korpora/korpora.py
Korpora/korpora_nsmc.py

#41 NSMCExample class 를 재활용이 가능한 LabeledSentence 로 교체
#41

Replace NSMCExample with LabeledSentence (fix #41)

---

Korpora/korpora.py
Korpora/korpora_chatbot_data.py
Korpora/korpora_kornli.py

Implement get_all_pairs and get_all_labels (fix #44)

---

Korpora/__init__.py
Korpora/korpora_custom.py

- [이전PR](https://github.com/ko-nlp/Korpora/pull/49) 에서 언급된 것처럼 아직 custom corpus classes 를 확인할 수 있는 데이터가 모두 존재하는 것이 아닙니다. 관련데이터가 Korpora 에서 모두 제공될 때 추가 테스트가 필요합니다.
- #47 의 주석을 추가
- #47 결과물 클래스들을 import 할 수 있도록 수정
#47, #48

Dev custom corpus

---

Korpora/__init__.py
Korpora/korpora.py
Korpora/korpora_nc_ner.py
Korpora/loader.py
tests/test_nc_ner.py

- 네이버 x 창원대 공개 NER 코퍼스를 패키지에 반영
- (words, tags) 형태의 데이터가 앞으로 많을 것으로 예상되는 만큼 WordTag, WordTagKorpusData 클래스 추가
https://github.com/ko-nlp/Korpora/issues/9

네이버 x 창원대 NER 코퍼스 #9

---

Korpora/__init__.py
Korpora/korpora_question_pair.py
Korpora/loader.py
tests/test_question_pair.py

- 질문쌍 데이터를 추가하는 PR입니다.
https://github.com/ko-nlp/Korpora/issues/12

질문쌍 데이터 추가 #12

---

Korpora/__init__.py
Korpora/korpora_chatbot_data.py
Korpora/korpora_namu_wiki.py
Korpora/korpora_nc_ner.py
Korpora/korpora_question_pair.py
Korpora/loader.py
Korpora/utils.py
requirements.txt
tests/test_korean_chatbot_data.py
tests/test_nc_ner.py
tests/test_question_pair.py

- 로컬에서 테스트를 하였습니다.
- 단 데이터의 크기가 크기 때문에 CI tools 에서 이를 매번 테스트하지 않는 방법을 고민해 보기로 @ratsgo 와 협의하였습니다.
#4 나무위키텍스트 코퍼스를 추가합니다.
#57 은 fetch 함수 부분의 input arguments 를 수정하지 않는 방법으로 namuwikitext korpus 를 만들었기 때문에 이 PR 에서는 고려하지 않습니다.

Namuwiki#4

---

Korpora/__init__.py
Korpora/korpora_korsts.py
Korpora/loader.py
tests/test_korsts.py

- KorSTS 코퍼스를 추가합니다
https://github.com/ko-nlp/Korpora/issues/11

KorSTS 코퍼스 추가 #11

---

Korpora/korpora_chatbot_data.py
Korpora/korpora_korean_petitions.py
Korpora/korpora_kornli.py
Korpora/korpora_namu_wiki.py
Korpora/korpora_nc_ner.py
Korpora/korpora_nsmc.py
Korpora/korpora_question_pair.py

- 기존 테스트 코드를 그대로 이용합니다.
description 의 컨벤션을 통일한 이슈입니다.
#27, #59

Dev unifying description

---

Korpora/korpora_chatbot_data.py
Korpora/korpora_korean_petitions.py
Korpora/korpora_kornli.py
Korpora/korpora_nc_ner.py
Korpora/korpora_nsmc.py
Korpora/korpora_question_pair.py

- 이전에 작성한 테스트 코드를 이용합니다.
데이터를 fetch 하는 기능을 init 함수에서 분리합니다.
#53, #59

Dev separate fetch

---

Korpora/__init__.py
Korpora/korpora_korean_hate_speech.py
Korpora/loader.py
tests/test_korean_hate_speech.py

Korean hate speech 말뭉치를 로드합니다. 해당 코퍼스는 다른 코퍼스와 파일 구조가 상이합니다. 원제작자의 파일 구조를 최대한 보존하기 위하여 각 데이터별로 load 함수를 작성하였습니다.
#13

Korean Hate Speech corpus 지원

---

Korpora/korpora_kcbert.py
Korpora/loader.py

- #73 이슈를 해결해야 합니다.
- KcBERT 코퍼스를 제공합니다.
- fetch 기능이 지원됩니다.
- 하지만 Korpora.fetch('kcbert') 는 #67 이 완료된 뒤에 추가 구현해야 합니다.
- 파일의 크기가 크기 때문에 text loading 을 하기 전에 사용자에게 확인을 받는 기능 (#63) 을 여기서 먼저 구현하였습니다.
- 동일한 기능은 namuwikitext 에서도 구현할 예정입니다.
#1, #53, #63, #67

KcBERT 학습데이터 지원

---

Korpora/korpora_namu_wiki.py

- #73 이슈를 해결해야 합니다.
Namuwikitext 로딩 시 train 데이터를 정말로 로딩할지 사용자에게 확인을 받습니다.
#63

파일의 크기가 큰 경우 로딩하기 전 사용자에게 경고와 동의를 얻는 기능 (#63)

---

Korpora/korpora_modu.py

- 테스트 코드가 존재하지 않는 abstract class 입니다.
모두의 말뭉치에 관련된 abstract korpus class 로, description 에 다음의 사실을 기술하였습니다.
- `Korpora==0.2.0` 에서 로딩 기능만 제공할 예정임
- Korpora 에서 fetch 기능을 제공할 수 없는 이유를 기술
#3

모두의 말뭉치 기능 제한 및 지원 계획 기술 (#3)

---

Korpora/about.py
README.md

- README.md만 수정하는 PR입니다.
각 데이터를 사용하는 방법을 안내하는 README 페이지를 보완하는 PR입니다.
https://github.com/ko-nlp/Korpora/issues/75

Update usage in README.md (#75)

---

Korpora/korpus_kcbert.py

KcBERTData 에서 getitem 기능을 지원합니다.
#83

Implement KcBERTData.__getitem__ (#83)

---

Korpora/korpus_namuwiki.py

url 을 제거한 버전으로 나무위키텍스트를 업데이트 합니다.
#84

Update namuwikitext v0.2 url (fix #84)

---

Korpora/utils.py

local 에 파일이 존재하더라도 remote 의 크기보다 작을 경우 다운로드를 진행합니다.
#90

Force download when size(local) < size(remote) (fix #90)

---

LICENSE
README.md

- ReadMe만 수정합니다.
README에 패키지 라이센스를 추가하는 PR입니다.
https://github.com/ko-nlp/Korpora/issues/88

License#88

---

Korpora/__init__.py
Korpora/korpus_korean_parallel.py
Korpora/loader.py
Korpora/utils.py
README.md
tests/test_korean_parallel.py

- Korean parallel corpus 에서 ko-en news 의 fetch / load 기능
- pytest
- rebase 과정에서 커밋 로그가 중복되어 이전의 PR #105 를 취소하고 다시 PR 보냅니다.
#93

Korean parallel corpus

---

Korpora/cli.py
setup.py

파이썬 패키지가 아닌, CLI 로 제공되는 코퍼스의 종류를 확인 / 코퍼스의 fetch 를 수행합니다.
#108

CLI fetch / list 

---

Korpora/korpus_modu_written.py
README.md

문어 말뭉치의 paragraph 를 하나의 데이터로 로딩하는 loader 와 사용법
#103, #114

모두의 말뭉치: 문어 말뭉치 loader

---

Korpora/korpus_modu_ne.py
README.md

개체명 분석 말뭉치 loader 와 사용법
#103, #116

모두의 말뭉치: 개체명 분석 말뭉치 loader

---

Korpora/__init__.py
Korpora/korpus_aihub_translation.py
Korpora/loader.py
README.md
requirements.txt

- 개인이 직접 로컬에 데이터를 받아야 하기 때문에 local test 코드를 [여기](https://github.com/ko-nlp/Korpora/issues/136#issuecomment-709594659)에 공유합니다.
AIHub 에서 제공하는 번역데이터 loader 와 사용법
#136

AIHub 번역데이터 loader

---

en-docs/corpuslist/korean_hate_speech.md

해당 PR은 홈페이지 영문 번역을 위한 git work의 첫 스텝으로 한국어 버젼의 README를 copy하였습니다.

Copied from Korean version (#139)

---

en-docs/corpuslist/korean_comments.md

Korean_comments.md의 번역을 위해 Korean version을 copy하였습니다.
#141  과 같은 양상으로 진행하겠습니다.

Copied korean_comments.md from Korean version (#139)

---

en-docs/corpuslist/korean_parallel_koen_news.md

번역을 위해 Korean parallel corpora를 copy했습니다.

Copy ko-en parallel corpus (#139)

---

en-docs/corpuslist/korean_parallel_koen_news.md

Korean Parallel Corpora를 번역하였습니다.
번역 상의 이슈는 없었습니다.

Translate ko-en parallel corpus (#139)

---

en-docs/corpuslist/korean_petitions.md

Korean Petitions 문서를 copy하고 번역하였습니다.
'청와대 국민청원'을 Blue House National Petition 으로 번역하였습니다.
이외 번역 상의 이슈는 없었습니다.

Copy and Translate Korean petitions

---

en-docs/corpuslist/kornli.md

KorNLI 문서를 copy하고 번역하였습니다.
중간에 '말뭉치 읽어들이기'가 Reading the corpus 로 번역되지 않은 것을 push 후 확인했습니다.
이부분 수정이 필요할 것 같습니다.

Copy and translate kornli.md

---

en-docs/corpuslist/question_pair.md

question_pair.md (en-docs/corpuslist/question_pair.md) 영문 번역 반영

Pages en pair

---

Korpora/korpus_modu_messenger.py
Korpora/korpus_modu_morpheme.py
Korpora/korpus_modu_ne.py
Korpora/korpus_modu_news.py
Korpora/korpus_modu_spoken.py
Korpora/korpus_modu_web.py
Korpora/korpus_modu_written.py

다른 코퍼스들과 통일성을 유지하기 위하여 `root_dir_or_paths`라는 변수를 `root_dir`로 수정합니다.
https://github.com/ko-nlp/Korpora/issues/121#issuecomment-727553167

Unify variable name: `root_dir_or_paths` -> `root_dir` (#121)

---

en-docs/corpuslist/modu_messenger.md
en-docs/corpuslist/modu_mp.md
en-docs/corpuslist/modu_ne.md
en-docs/corpuslist/modu_news.md
en-docs/corpuslist/modu_spoken.md
en-docs/corpuslist/modu_web.md
en-docs/corpuslist/modu_written.md
ko-docs/corpuslist/aihub_translation.md
ko-docs/corpuslist/modu_messenger.md
ko-docs/corpuslist/modu_mp.md
ko-docs/corpuslist/modu_ne.md
ko-docs/corpuslist/modu_news.md
ko-docs/corpuslist/modu_spoken.md
ko-docs/corpuslist/modu_web.md
ko-docs/corpuslist/modu_written.md

영어 설명 문서에서 root_dir_or_paths라고 표현된 변수명을 root_dir로 통일하는 PR입니다.
한국어 문서도 이같은 변경이 이뤄졌기 때문에([관련 PR](https://github.com/ko-nlp/Korpora/pull/167)) 최신 pages 브랜치에 rebase해 관련 커밋이 반영되도록 했습니다.
(이 브랜치를 pages에 PR하여도 충돌이 나지 않는 걸 확인했습니다)
https://github.com/ko-nlp/Korpora/issues/121

Fix en pages

---

en-docs/corpuslist/kowikitext.md

Kowikitext.md를 번역하였습니다.
별도의 번역 상 이슈는 없었으며, 첫 줄의 소개 문구를 번안하는 데에 고민이 조금 되었는데 괜찮은지 확인해 주시면 좋을 것 같습니다 ㅎㅎ

Copy and translate kowikitext.md

---

en-docs/corpuslist/aihub_translation.md

aihub_translation.md를 번역하였습니다.
데이터 설명에서 
`영어 파일 이름`을 `한글 파일 이름`과 대응되게 하기 위해 Latin alphabet file names 로 표현하였으며, 
ko-docs에서 SpokenTranslationKorpus 로 표기된 부분이 한 곳 있어 ConversationTranslationKorpus 로 변경하였습니다.

Translate aihub_translation.md

---

README.md

새로운 README에 이름을 추가하였습니다.
없습니다!

Add Wonik to Readme#148

---

Korpora/task_lmdata.py

lmdata 로 데이터 추출시, namuwiki와 kowiki의 path 가 맞지 않는 부분을 수정하였습니다.

Fix paths in lmdata task

---

Korpora/task_fetch.py

`korpus --fetch all` 실행시 에러를 수정하였습니다.

Fix corpus argument in `task_fetch.py`

---

Korpora/task_lmdata.py

lmdata에 open subtitle 를 추가하였습니다.

Add open-subtitles in `task_lmdata.py`

---

Korpora/korpus_aihub_translation.py
requirements.txt

- 최신 버전의 xlrd가 더이상 xlsx를 지원하지 않음에 따라, openpyxl로 코드를 변경하였습니다.
- Root directory 옵션이 사용될 때, 데이터 저장 구조의 일관성을 위하여 root 옵션이 없을 때와 동일하게 `<Root directory>/AIHub_Translation` 을 사용하도록 수정하였습니다.

Fix loading xlsx files in `korpus_aihub_translation.py`

---

README.md

- README 에 `Korpora.corpus_list_en()` 의 사용 예시를 수정합니다.
#181 #182

Update usage; `Korpora.corpus_list_en()` (#181)
